### PR TITLE
added plot directive

### PR DESCRIPTION
**Pull request by monroews**
finalizing draft of Introduction

### CODE REVIEW

**Comment by juanchon998** [comment]
Is this ready to be merged if it passes travis?

**Comment by monroews** [comment]
Sure. But I'm discovering that the plot directive doesn't work.  So I'm thinking I'll revert to using code to create the figure.
I tried...
.. plot::

  from aide_design.play import*
  def v_t(D_particle,density_particle,Temperature):
    return (D_particle**2*pc.gravity *(density_particle - pc.density_water(Temperature))/(18*pc.viscosity_kinematic(Temperature)*pc.density_water(Temperature))).to(u.m/u.s)
  clay = 2650 * u.kg/u.m**3
  organic = 1040 * u.kg/u.m**3
  Temperature = 20 * u.degC
  D_particle = np.logspace(-6,-3)*u.m
  fig, ax = plt.subplots()
  ax.loglog(D_particle.to(u.m),v_t(D_particle,clay,Temperature).to(u.m/u.s))
  ax.loglog(D_particle.to(u.m),v_t(D_particle,organic,Temperature).to(u.m/u.s))
  ax.set(xlabel='Particle diameter (m)', ylabel='Terminal velocity (m/s)')
  ax.legend(["clay or sand","organic particle"])
  plt.show()

And I get no figure in html...

**Comment by juanchon998** [comment]
Hmm. I haven't been able to plot either so I don't think I'll be terrible helpful. Did you get any errors or just no figure? @clare45  may know more!

**Comment by monroews** [comment]
I'm hoping to merge and publish this pending Travis approval.

**Comment by juanchon998** [comment]
Also @monroews  make sure to add at least 1 reviewer to each pull request that you open!

**Comment by monroews** [comment]
At this stage of development, what is the role of review? I ask because the textbook will need a review, but I don't think a review is necessary for each pull request.

**Pull request merged**
